package br.com.ocr;

public enum PageSegmentationMode {
	_00_ORIENTATION_AND_SCRIPT_DETECTION_ONLY("0"),
	_01_AUTOMATIC_PAGE_SEGMENTATION_WITH_OSD("1"),
	_02_AUTOMATIC_PAGE_SEGMENTATION_BUT_NO_OSD_OR_OCR("2"),
	_03_FULLY_AUTOMATIC_PAGE_SEGMENTATION_BUT_NO_OSD("3"),
	_04_ASSUME_A_SINGLE_COLUMN_OF_TEXT_OF_VARIABLE_SIZES("4"),
	_05_ASSUME_A_SINGLE_UNIFORM_BLOCK_OF_VERTICALLY_ALIGNED_TEXT("5"),
	_06_ASSUME_A_SINGLE_UNIFORM_BLOCK_OF_TEXT("6"),
	_07_TREAT_THE_IMAGE_AS_A_SINGLE_TEXT_LINE("7"),
	_08_TREAT_THE_IMAGE_AS_A_SINGLE_WORD("8"),
	_09_TREAT_THE_IMAGE_AS_A_SINGLE_WORD_IN_A_CIRCLE("9"),
	_10_TREAT_THE_IMAGE_AS_A_SINGLE_CHARACTER("10"),
	_11_SPARSE_TEXT("11"),
	_12_SPARSE_TEXT_WITH_OSD("12"),
	_13_RAW_LINE("13");
    
    private final String value;
    
    public String getValue() {
    	return this.value;
    }
    
    private PageSegmentationMode(String value) {
        this.value = value;
    }
}